environment variable with shell is allowd
ansible-community/ansible-lint pull request #1200
Opened 2021-01-04 09:08 UTC by senyoltw

The default rule 304 description is  “Environment variables should be passed to ``shell`` or ``command`` through environment argument“.  but in the code only ``command``, so need to fix it.
Reference: Pull Request https://github.com/ansible-community/ansible-lint/pull/477

2021-01-04 09:42 UTC, ssbarnea requested changes
There is some confusion as both modules accept environment argument but on command you cannot put in-line vars.

To avoid confusing users even more, lets rephrase both shortdesc and description to make this clear. This rule is only about command module. I am thinking about something like: 

Command module does not accept setting environmnet variables inline. 

Use environment argument to set variables or use shell module which accepts both.

2021-01-05 04:33 UTC, senyoltw commented
Thanks for the review. I fixed it.

2021-01-05 11:20 UTC, ssbarnea approved these changes

2021-01-05 12:55 UTC, tadeboro approved these changes

2021-01-05 13:01 UTC, merged