only warn about failing git discovery when increased verbosity level
ansible-community/ansible-lint pull request #1414
Opened 2021-02-27 02:43 UTC by konstruktoid

```console
$ ansible-lint test.yml 
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: test.yml
WARNING  Listing 1 violation(s) that are fatal
no-changed-when: Commands should not change things if nothing needs doing
test.yml:7 Task/Handler: Register a command

You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - no-changed-when  # Commands should not change things if nothing needs doing
Finished with 1 failure(s), 0 warning(s) on 1 files.
$ ansible-lint -v test.yml 
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: test.yml
INFO     Discovering files to lint: git ls-files -z *.yaml *.yml
WARNING  Failed to discover yaml files to lint using git: fatal: not a git repository (or any of the parent directories): .git
INFO     Executing syntax check on test.yml (0.78s)
WARNING  Listing 1 violation(s) that are fatal
no-changed-when: Commands should not change things if nothing needs doing
test.yml:7 Task/Handler: Register a command

You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - no-changed-when  # Commands should not change things if nothing needs doing
Finished with 1 failure(s), 0 warning(s) on 1 files.
```

closes #1410

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

2021-02-27 11:25 UTC, konstruktoid commented
Don't merge just yet, will update wording and such.

2021-02-27 12:51 UTC, ssbarnea requested changes
Python logging already has support for filtering messages based on configured verbosity so there is no need for such conditions. The real bug is that verbosity level for logging is not current set, and this is why you still see the message when you should not.

The bug is real, but that's not the real proper fix for it.  I will try to find time to asdress it as is not really easy.

2021-02-27 15:18 UTC, konstruktoid commented
No, this isn't the proper fix for that bug and wasn't really meant to be.
Should I close and let you fix the logging?

2021-03-11 16:07 UTC, ssbarnea commented
Closing as code in master already respects -q option, silencing this message.

2021-03-11 16:07 UTC, closed without merging