Add opt-in rule to check whether FQCN is used for builtins
ansible-community/ansible-lint pull request #1614
Opened 2021-06-07 11:40 UTC by StopMotionCuber

As I have written in #1587, we currently have a regression for our custom rule that checks whether FQCNs are used everywhere.
As @ssbarnea suggested there, I added this rule upstream and made it opt-in. To not break current pipelines, it is by default turned _off_ in the CI. I needed to change the `rule_runner` fixture, such that this rule is ran for the `rule_runner` nevertheless (this also seems like the more sensible default to me, as you include a specific rule there and expect it to be run).

This is my first contribution to this project, so feedback is welcome

2021-06-07 14:22 UTC, tadeboro requested changes
I like the rule (for the playbooks I help maintain, we use FQCNs in all tasks). But this rule should definitely be disabled by default because as far as I know, there is no plan to deprecate bare name usage.

I did add a few nitpicks, but apart from that, the rule looks good to me.

2021-06-07 14:22 UTC, tadeboro commented on src/ansiblelint/rules/FQCNBuiltinsRule.py
> +        return False
```suggestion
        return task["action"]["__ansible_module_original__"] in builtins
```

2021-06-07 14:39 UTC, StopMotionCuber commented
Thanks for your review @tadeboro, I adapted the code to include your comments

2021-06-07 15:11 UTC, tadeboro approved these changes

2021-06-07 15:19 UTC, felixfontein commented on src/ansiblelint/rules/FQCNBuiltinsRule.py
> +    shortdesc = "Use fqcn for builtins"
```suggestion
    shortdesc = "Use FQCN for builtin actions"
```
The rule does not check plugins.

2021-06-07 17:35 UTC, tadeboro approved these changes

2021-06-07 17:36 UTC, felixfontein approved these changes

2021-06-09 17:11 UTC, ssbarnea approved these changes

2021-06-09 17:11 UTC, merged