Add ability to load .config/.ansible-lint
ansible-community/ansible-lint pull request #1822
Opened 2022-01-21 11:59 UTC by ssbarnea

2022-01-21 12:28 UTC, webknjaz requested changes
I've never seen other projects using a trailing dot when the config is in a subdirectory. In that case, it's usually only the directory itself that is dotted.
I'd go for `.config/ansible-lint`, then. Alternatively, there could be support for specifying a different path via `pyproject.toml` instead of hardcoding one string — because it's not a widely accepted standard and some projects may already have some other directory for config adopted.
Also, I would expect tests for this kind of patch.

2022-01-21 12:39 UTC, ssbarnea commented
> I've never seen other projects using a leading dot when the config is in a subdirectory. In that case, it's usually only the directory itself that is dotted. I'd go for `.config/ansible-lint`, then. Alternatively, there could be support for specifying a different path via `pyproject.toml` instead of hardcoding one string — because it's not a widely accepted standard and some projects may already have some other directory for config adopted. Also, I would expect tests for this kind of patch.

I am not going to go for the configure the config file location rabbit hole.

I considered a different name without the dot but that would add extra complexity and I prefer to KISS. Telling people that just move existing config filename without asking them to rename them is easier. Also, changing the filename would require changes in other places like json schemas that detect the configuration of ansible-lint. 

But I will add tests, that is indeed a genuine comment. Anything else should be considered as something for the future, like having a proper yml file extension would not be a bad idea, just outside the scope.

2022-01-21 13:53 UTC, tadeboro commented
I think this is not needed. Ansible Lint already consults too many locations when it searches for the config file. It is bad enough that the configuration loader can retrieve configuration from a file that has nothing to do with the current project.

As for configuring the config file path: we already allow this (`-c` command-line switch). So adding support for this would probably be a lesser evil compared to another magic search we are trying to introduce here.

2022-02-16 14:39 UTC, cognifloyd approved these changes

2022-03-05 15:29 UTC, merged