Make FQCN import tasks include their relevant files for checking
ansible-community/ansible-lint pull request #1854
Opened 2022-02-07 21:05 UTC by ryaner

Tasks can come in in either the short format or the FQCN format
as this is called before noramlize_task functions.

2022-02-07 21:07 UTC, ryaner commented
Another option for fixing would be to split the string down on L328 `(k, v) = item`.
`k` can either be `import_tasks` or `ansible.builtin.import_tasks`.
Including the cases where the functions have FQCNs is slightly faster given the number of times the function is called.

2022-02-08 08:29 UTC, ssbarnea requested changes
The fix seems logic and thanks for creating the PR.

Also, please update the tests in order to include a regression prevention measure. Think about a change, even to existing test covering the same functionality, that would fail if we remove your fix.

2022-02-08 18:01 UTC, ryaner commented
I combined in the fix for #1615 as adding the FQCN into the tests caused the `All tasks should be named` to trigger during the tests. If you'd prefer I separate things I can do so, making this dependant on a PR for #1615.

This does not fix the fact that `import_` calls do not trigger the FQCN ruleset. I don't see a way to pass the tasks to only a subset of the rulesets.

2022-02-09 11:55 UTC, ssbarnea approved these changes

2022-02-17 17:05 UTC, merged