Ease creation of MatchError from inside rules
ansible-community/ansible-lint pull request #956
Opened 2020-08-14 15:13 UTC by ssbarnea

Adds utility method for creation of MatchError(s) from inside Rules,
so we can easily reuse it.

2020-08-25 10:53 UTC, webknjaz requested changes
I don't see a point of having another level of indirection. This is just a proxy-method and I can't imagine how I could justify merging this change.

2020-08-25 10:58 UTC, ssbarnea commented
> I don't see a point of having another level of indirection. This is just a proxy-method and I can't imagine how I could justify merging this change.

Updated description to mention reasoning. While it does not look as required for current use, it is needed for upcoming work. This change is a spinoff.

2020-08-25 11:42 UTC, webknjaz commented
I still don't see a point: if you want to instantiate a `MatchError` go and do it. Adding a proxy method that only bypasses the args to the initializer doesn't contribute to simplicity in any way.

2020-08-29 23:34 UTC, greg-hellings commented
It's already reduced code redundancy here. If this method ends up being used over and over in future work, then it continues to save redundancy each time.

2020-12-13 09:48 UTC, merged